def interrupt_on_error(error_msg: str):
    print("Error: " + error_msg)
    exit(-1)
